"""added participants field

Revision ID: 95761d55b7d5
Revises: 
Create Date: 2022-04-10 20:20:05.687976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95761d55b7d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_stats', sa.Column('participants', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_stats', 'participants')
    # ### end Alembic commands ###
